# Generated by Claude Code

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.EmailField(default='noreply@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
