# Generated by Django 4.2.7 on 2025-11-25 19:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_relations', to='products.product')),
                ('to_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_relations', to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, related_name='related_to_products', through='products.ProductRelation', to='products.product'),
        ),
        migrations.AddIndex(
            model_name='productrelation',
            index=models.Index(fields=['from_product'], name='products_pr_from_pr_aee38f_idx'),
        ),
        migrations.AddIndex(
            model_name='productrelation',
            index=models.Index(fields=['to_product'], name='products_pr_to_prod_a41b61_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productrelation',
            unique_together={('from_product', 'to_product')},
        ),
    ]
