# Generated by Django 4.2.7 on 2025-11-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_product_code'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productspec',
            constraint=models.UniqueConstraint(fields=('product', 'code'), name='unique_product_spec_per_product_code'),
        ),
    ]
