# Generated by Django 4.2.7 on 2025-12-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productspec_unique_product_spec_per_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, default='', max_length=64, unique=True),
        ),
    ]
