# Generated by Django 4.2.7 on 2026-06-04 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_delete_productspec_delete_productspecification_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technicalspec',
            options={'ordering': ['created_at'], 'verbose_name': 'Especificación Técnica', 'verbose_name_plural': 'Especificaciones Técnicas'},
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='dimensions',
        ),
    ]
