# Generated by Django 4.2.7 on 2026-07-15 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_unaccent_extension'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['created_at']},
        ),
    ]
