# Generated by Django 5.2 on 2026-07-23 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
        ('products', '0013_alter_productvariant_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='root_category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='articulo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='cas',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='sedronar',
            field=models.CharField(blank=True, default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='esp_attachment',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='esp_products',
                to='attachments.attachment',
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='hds_attachment',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='hds_products',
                to='attachments.attachment',
            ),
        ),
    ]
