# Generated by Django 4.2.7 on 2026-09-10 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_brand_slug'),
        ('products', '0015_product_spec_table'),
    ]

    operations = [
    ]
