# Generated by Django 4.2.7 on 2026-03-10 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketpriority_ticketstate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='numero_de_serie',
            field=models.CharField(default='', max_length=255),
        ),
    ]
