# Generated by Django 4.2.7 on 2026-03-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_serviceticket_numero_de_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='marca',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='modelo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='producto_laqq',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
