# Generated by Django 4.2.7 on 2025-12-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_remove_quoteitem_product_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
