# Generated by Django 4.2.7 on 2026-02-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_alter_quote_quote_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotetype',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
