# Generated by Django 4.2.7 on 2026-02-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_alter_quotetype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotetype',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
