# Generated by Django 4.2.7 on 2026-02-09 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_alter_quotetype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_type',
            field=models.ForeignKey(default='standard', on_delete=django.db.models.deletion.PROTECT, to='quotes.quotetype'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='state',
            field=models.ForeignKey(default='pending', on_delete=django.db.models.deletion.PROTECT, to='quotes.quotestate'),
        ),
    ]
