# Generated by Django 4.2.7 on 2026-03-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_alter_quote_quote_type_alter_quote_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
