# Generated by Django 4.2.7 on 2026-04-06 04:09

from django.db import migrations, models
import django.db.models.deletion


def check_and_add_field(apps, schema_editor):
    """
    Agrega el campo fixed_spec solo si no existe.
    Esto previene errores cuando la columna ya existe en producción.
    """
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name='quotes_quoteitem' AND column_name='fixed_spec_id';
        """)
        exists = cursor.fetchone()

        if not exists:
            # Solo crear la columna si no existe
            cursor.execute("""
                ALTER TABLE quotes_quoteitem
                ADD COLUMN fixed_spec_id UUID NULL
                REFERENCES products_productspec(id) ON DELETE SET NULL;
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_brand_alter_product_category'),
        ('quotes', '0007_quote_observaciones'),
    ]

    operations = [
        migrations.RunPython(check_and_add_field, migrations.RunPython.noop),
    ]
