# Generated by Django 4.2.7 on 2026-04-09 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_brand_alter_product_category'),
        ('quotes', '0008_fix_quote_item_use_productspec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteitem',
            name='fixed_spec',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='quote_items',
                to='products.productspec'
            ),
        ),
    ]
