# Generated by Django 4.2.7 on 2026-04-29 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_producttechnicalspec_productvariant_technicalspec_and_more'),
        ('quotes', '0009_fix_productspec_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteitem',
            name='fixed_spec',
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_items', to='products.productvariant'),
        ),
    ]
