# Generated by Django 4.2.7 on 2026-05-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_remove_quoteitem_fixed_spec_quoteitem_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='specs',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
