# Generated by Django 4.2.7 on 2025-11-25 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0002_alter_productaccessory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessory',
            options={'verbose_name': 'Accessory', 'verbose_name_plural': 'Accessories'},
        ),
    ]
