# Generated by Django 4.2.7 on 2025-11-25 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productaccessory',
            options={'verbose_name': 'Product Accessory', 'verbose_name_plural': 'Product Accessories'},
        ),
    ]
