# Generated by Django 4.2.7 on 2025-11-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['attachable_type', 'attachable_id'], name='idx_attachments_attachable'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['file_name'], name='idx_attachments_file_name'),
        ),
    ]
