# Generated by Django 4.2.7 on 2026-01-06 18:07

import attachments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_attachment_idx_attachments_attachable_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='data',
        ),
        migrations.AddField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=attachments.models.attachment_upload_to),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
