# Generated by Django 4.2.7 on 2026-01-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0003_alter_attachment_options_remove_attachment_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='role',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('manual', 'Manual'), ('datasheet', 'Datasheet'), ('other', 'Other')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachable_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachable_type',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
