# Generated by Django 4.2.7 on 2026-01-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0005_add_generic_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='content_type_str',
            field=models.CharField(blank=True, help_text='MIME type del archivo', max_length=100, null=True),
        ),
    ]
