# Generated by Django 4.2.7 on 2025-11-25 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteitem',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='quoteitem',
            name='product_name',
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
    ]
