# Generated by Django 4.2.7 on 2025-12-24 19:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspec',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_specs', to='products.product'),
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(help_text='Nombre de la especificación (ej: Voltaje, Material, Temperatura)', max_length=100)),
                ('value', models.TextField(help_text='Valor de la especificación (ej: 220V, Acero inoxidable)')),
                ('unit', models.CharField(blank=True, default='', help_text='Unidad de medida opcional (ej: V, °C, ml, kg)', max_length=20)),
                ('display_order', models.IntegerField(default=0, help_text='Orden de visualización (menor número = primero)')),
                ('is_visible', models.BooleanField(default=True, help_text='Mostrar esta especificación en el frontend')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='Producto al que pertenece esta especificación', on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_specifications', to='products.product')),
            ],
            options={
                'verbose_name': 'Especificación Dinámica',
                'verbose_name_plural': 'Especificaciones Dinámicas',
                'ordering': ['display_order', 'key'],
                'indexes': [models.Index(fields=['product', 'display_order'], name='products_pr_product_279b7f_idx')],
            },
        ),
    ]
